name: Publish the mod

on:
  release:
    types: [published]


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false

      - name: Generate resources with Gradle
        run: ./gradlew runDatagenClient

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          VERSION_NAME: ${{ github.event.release.name }}

      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
